### PR TITLE
3.3.8 second paragraph: Fix English for inter-character spacing of ruby #80

### PR DESCRIPTION
**Pull request by macnmm**
(edit by @himorin to add reference link, this is for #80 )

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/jlreq/pull/81.html" title="Last updated on Jun 20, 2019, 5:11 PM UTC (94590cb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/jlreq/81/8da8f10...94590cb.html" title="Last updated on Jun 20, 2019, 5:11 PM UTC (94590cb)">Diff</a>

### CODE REVIEW

**Comment by himorin** [comment]
not sure exactly, but second comma added to line 4043 is correct?

**Comment by macnmm** [comment]
> not sure exactly, but second comma added to line 4043 is correct?

I think it makes the clause more readable -- "...avoid misreading of the layout, and maintain its beauty" could be a further improvement if the embedded commas bother people.

In fact, the original could say "...avoid misreading of the base text, as well as maintain the beauty of the layout.", but instead the clause "avoid misreading and maintain the beauty of" makes it ambiguous what is the object of "misreading". In my opinion, anyway. :)

I think I like that last edit better now that I look at it. I will propose it.

**Review by himorin — APPROVED** [review]

**Comment by himorin** [comment]
note: may need to think about https://github.com/w3c/jlreq/issues/85#issuecomment-503836495 also

**Comment by xfq** [comment]
#85 is a larger issue around the use of the word "spaces". Since we already have a PR for #80 (which is this PR), I think other instances of "spaces" can be fixed separately.

**Pull request closed without merging**
