### PR TITLE
fix https://github.com/w3c/jlreq/issues/10, https://github.com/w3c/jlreq/issues/15

### PR DESCRIPTION
**Pull request by macnmm**
tweak the English for 2.5.2 spacing of figures in book layout

tweak the description of ruby spacing

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/jlreq/pull/62.html" title="Last updated on Jun 12, 2019, 2:58 AM UTC (65d8852)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/jlreq/62/8791dbb...65d8852.html" title="Last updated on Jun 12, 2019, 2:58 AM UTC (65d8852)">Diff</a>

### CODE REVIEW

**Comment by r12a** [comment]
Generally, this LGTM. I would observe that 'letters' are not always the same as 'characters', since ruby could theoretically contain a decomposed á which should be treated as a single unit.  That said, the use cases being described here are for use of Japanese annotations, so there may not be much difference between the two terms.

**Comment by macnmm** [comment]
> Generally, this LGTM. I would observe that 'letters' are not always the same as 'characters', since ruby could theoretically contain a decomposed á which should be treated as a single unit. That said, the use cases being described here are for use of Japanese annotations, so there may not be much difference between the two terms.

Ah, I use the term "codepoint" for something that is part of a "character". A "letter" to me is alphanumeric and falls outside kana (could be I am alone in this?)

**Comment by xfq** [comment]
> Ah, I use the term "codepoint" for something that is part of a "character". A "letter" to me is alphanumeric and falls outside kana (could be I am alone in this?)

Not in [CSS Text](https://drafts.csswg.org/css-text-3/#characters), at least ;)

**Comment by himorin** [comment]
Generally LGTM, but second part of this PR seems not for #15 (nor #10 ), and  also I think two parts should be better in separated.

**Comment by macnmm** [comment]
> Generally LGTM, but second part of this PR seems not for #15 (nor #10 ), and also I think two parts should be better in separated.

Yes, I meant to keep the #10 and #15 separated, but then I realized this requires me to create a new branch for each PR which I hadn't done. I was thinking it was ok to accumulate English fixes in a single branch and re-use it, but if you want branches for each tweak, I can do that... @himorin what would you like?

**Comment by macnmm** [comment]
closing this to make new smaller PRs

**Pull request closed without merging**
