### PR TITLE
Add lang attribute to EDITING.md

### LINKED ISSUE #213: Add lang attribute to EDITING.md
In [EDITING.md](https://github.com/w3c/jlreq/blob/gh-pages/EDITING.md), the markup examples only contain the `its-locale-filter-list` attribute, but not the `lang` attribute. We should probably add `lang` to the examples.

### PR DESCRIPTION
**Pull request by xfq**
Fix #213.

### CODE REVIEW

**Comment by xfq** [comment]
I added `lang` to the `img` elements as well, but they actually do not have the `lang` attributes in the current jlreq document. Should I remove them in EDITING.md, or do we need to add `lang` for the `img` elements (because it specifies the language for the text in `alt`)?

**Comment by himorin** [comment]
I think some img elements in JLreq Note has lang="ja" (but none for lang="en"?)

**Comment by r12a** [comment]
Thanks for preparing this @xfq .  I think we should keep the recommendation to use the lang attribute for images too.  As you say, this can be useful for alt or title text.  I'm not sure whether we need to retrofit that to the jlreq doc, if it's currently working ok.

We should also change the advice about linking to sections and figures, to recommend use of [[[ ]]] rather than the `<a> `markup currently recommended.

**Comment by xfq** [comment]
> Thanks for preparing this @xfq . I think we should keep the recommendation to use the lang attribute for images too. As you say, this can be useful for alt or title text. I'm not sure whether we need to retrofit that to the jlreq doc, if it's currently working ok.

OK. Could you merge this PR?

> We should also change the advice about linking to sections and figures, to recommend use of [[[ ]]] rather than the `<a> `markup currently recommended.

I just submitted https://github.com/w3c/jlreq/pull/221 for this.

**Pull request merged**
