### PR TITLE
Added Japanese version to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by himorin**
Added Japanese translation at the end of CONTRIBUTING.md

### CODE REVIEW

**Comment by r12a** [comment]
Is there some reason this has not yet been merged ?

**Comment by watilde** [comment]
+1 to ship.

**Comment by himorin** [comment]
asking final check to ship (as review), could not point Kida-san's account - do anyone know one??

**Review by kidayasuo — APPROVED** [review]
Approving with one comment which is not a condition for the approval.

The translation of "the employer has waived such rights for the contributions to W3C" (the last part under "Copyright") is "雇用者が W3C への貢献に対する権利を放棄したこと". It could be misinterpreted as "the employer has waived rights for making contributions to W3C". I suggest to make it "貢献物" or "貢献内容" to make it clear that it is about the thing that has been contributed.

The term "contribution(s)" is used in two senses in this document; 1) the act of contribution, 2) the thing that has been contributed. The first sense is always translated to "貢献を行う". The second sense, which is the majority, is translated to "貢献", "内容", "貢献内容", "貢献部分". It might be better to make it consistent as "貢献物" or "貢献内容".

**Comment by himorin** [comment]
- changed from "貢献に対する権利を放棄" to "貢献内容に対する権利を放棄" for the first point
- for "Contribution(s)", I've updated to "貢献内容" as much as possible. I somehow wondered section title "Contributions" is close to 1) or 2), but unified as things but not action.

**Comment by r12a** [comment]
@himorin can we ship this change now?

**Comment by himorin** [comment]
@r12a ah, sure, yes. sorry for delay after r+...

**Comment by kidayasuo** [comment]
👍 Thank you!

**Pull request merged**
